// Auto-generated by scripts/buildLibrary.js — do not edit by hand.
// Source: yuhonas/free-exercise-db (public domain)

export interface Exercise {
  id: string;
  name: string;
  bodyPart: string;
  target: string;
  equipment: string;
  difficulty: string;
  instructions: string[];
  secondaryMuscles: string[];
  images: string[];
}

export const MOVES: Exercise[] = [
  {
    id:               "Bodyweight_Squat",
    name:             "Squat",
    bodyPart:         "strength",
    target:           "quadriceps",
    equipment:        "body only",
    difficulty:       "beginner",
    instructions:     ["Stand with your feet shoulder width apart. You can place your hands behind your head. This will be your starting position.","Begin the movement by flexing your knees and hips, sitting back with your hips.","Continue down to full depth if you are able,and quickly reverse the motion until you return to the starting position. As you squat, keep your head and chest up and push your knees out."],
    secondaryMuscles: ["glutes","hamstrings"],
    images:           ["https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Bodyweight_Squat/0.jpg","https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Bodyweight_Squat/1.jpg"],
  },
  {
    id:               "Pushups",
    name:             "Push-up",
    bodyPart:         "strength",
    target:           "chest",
    equipment:        "body only",
    difficulty:       "beginner",
    instructions:     ["Lie on the floor face down and place your hands about 36 inches apart while holding your torso up at arms length.","Next, lower yourself downward until your chest almost touches the floor as you inhale.","Now breathe out and press your upper body back up to the starting position while squeezing your chest.","After a brief pause at the top contracted position, you can begin to lower yourself downward again for as many repetitions as needed."],
    secondaryMuscles: ["shoulders","triceps"],
    images:           ["https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Pushups/0.jpg","https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Pushups/1.jpg"],
  },
  {
    id:               "Pullups",
    name:             "Pull-up",
    bodyPart:         "strength",
    target:           "lats",
    equipment:        "body only",
    difficulty:       "beginner",
    instructions:     ["Grab the pull-up bar with the palms facing forward using the prescribed grip. Note on grips: For a wide grip, your hands need to be spaced out at a distance wider than your shoulder width. For a medium grip, your hands need to be spaced out at a distance equal to your shoulder width and for a close grip at a distance smaller than your shoulder width.","As you have both arms extended in front of you holding the bar at the chosen grip width, bring your torso back around 30 degrees or so while creating a curvature on your lower back and sticking your chest out. This is your starting position.","Pull your torso up until the bar touches your upper chest by drawing the shoulders and the upper arms down and back. Exhale as you perform this portion of the movement. Tip: Concentrate on squeezing the back muscles once you reach the full contracted position. The upper torso should remain stationary as it moves through space and only the arms should move. The forearms should do no other work other than hold the bar.","After a second on the contracted position, start to inhale and slowly lower your torso back to the starting position when your arms are fully extended and the lats are fully stretched.","Repeat this motion for the prescribed amount of repetitions."],
    secondaryMuscles: ["biceps","middle back"],
    images:           ["https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Pullups/0.jpg","https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Pullups/1.jpg"],
  },
  {
    id:               "Bodyweight_Walking_Lunge",
    name:             "Lunge",
    bodyPart:         "strength",
    target:           "quadriceps",
    equipment:        "",
    difficulty:       "beginner",
    instructions:     ["Begin standing with your feet shoulder width apart and your hands on your hips.","Step forward with one leg, flexing the knees to drop your hips. Descend until your rear knee nearly touches the ground. Your posture should remain upright, and your front knee should stay above the front foot.","Drive through the heel of your lead foot and extend both knees to raise yourself back up.","Step forward with your rear foot, repeating the lunge on the opposite leg."],
    secondaryMuscles: ["calves","glutes","hamstrings"],
    images:           ["https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Bodyweight_Walking_Lunge/0.jpg","https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Bodyweight_Walking_Lunge/1.jpg"],
  },
  {
    id:               "Plank",
    name:             "Plank",
    bodyPart:         "strength",
    target:           "abdominals",
    equipment:        "body only",
    difficulty:       "beginner",
    instructions:     ["Get into a prone position on the floor, supporting your weight on your toes and your forearms. Your arms are bent and directly below the shoulder.","Keep your body straight at all times, and hold this position as long as possible. To increase difficulty, an arm or leg can be raised."],
    secondaryMuscles: [],
    images:           ["https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Plank/0.jpg","https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Plank/1.jpg"],
  },
  {
    id:               "Dumbbell_Bicep_Curl",
    name:             "Bicep Curl",
    bodyPart:         "strength",
    target:           "biceps",
    equipment:        "dumbbell",
    difficulty:       "beginner",
    instructions:     ["Stand up straight with a dumbbell in each hand at arm's length. Keep your elbows close to your torso and rotate the palms of your hands until they are facing forward. This will be your starting position.","Now, keeping the upper arms stationary, exhale and curl the weights while contracting your biceps. Continue to raise the weights until your biceps are fully contracted and the dumbbells are at shoulder level. Hold the contracted position for a brief pause as you squeeze your biceps.","Then, inhale and slowly begin to lower the dumbbells back to the starting position.","Repeat for the recommended amount of repetitions."],
    secondaryMuscles: ["forearms"],
    images:           ["https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Bicep_Curl/0.jpg","https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Bicep_Curl/1.jpg"],
  },
  {
    id:               "Dumbbell_Bench_Press",
    name:             "Bench Press",
    bodyPart:         "strength",
    target:           "chest",
    equipment:        "dumbbell",
    difficulty:       "beginner",
    instructions:     ["Lie down on a flat bench with a dumbbell in each hand resting on top of your thighs. The palms of your hands will be facing each other.","Then, using your thighs to help raise the dumbbells up, lift the dumbbells one at a time so that you can hold them in front of you at shoulder width.","Once at shoulder width, rotate your wrists forward so that the palms of your hands are facing away from you. The dumbbells should be just to the sides of your chest, with your upper arm and forearm creating a 90 degree angle. Be sure to maintain full control of the dumbbells at all times. This will be your starting position.","Then, as you breathe out, use your chest to push the dumbbells up. Lock your arms at the top of the lift and squeeze your chest, hold for a second and then begin coming down slowly. Tip: Ideally, lowering the weight should take about twice as long as raising it.","Repeat the movement for the prescribed amount of repetitions of your training program."],
    secondaryMuscles: ["shoulders","triceps"],
    images:           ["https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Bench_Press/0.jpg","https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Bench_Press/1.jpg"],
  },
  {
    id:               "Wide-Grip_Lat_Pulldown",
    name:             "Lat Pulldown",
    bodyPart:         "strength",
    target:           "lats",
    equipment:        "cable",
    difficulty:       "beginner",
    instructions:     ["Sit down on a pull-down machine with a wide bar attached to the top pulley. Make sure that you adjust the knee pad of the machine to fit your height. These pads will prevent your body from being raised by the resistance attached to the bar.","Grab the bar with the palms facing forward using the prescribed grip. Note on grips: For a wide grip, your hands need to be spaced out at a distance wider than shoulder width. For a medium grip, your hands need to be spaced out at a distance equal to your shoulder width and for a close grip at a distance smaller than your shoulder width.","As you have both arms extended in front of you holding the bar at the chosen grip width, bring your torso back around 30 degrees or so while creating a curvature on your lower back and sticking your chest out. This is your starting position.","As you breathe out, bring the bar down until it touches your upper chest by drawing the shoulders and the upper arms down and back. Tip: Concentrate on squeezing the back muscles once you reach the full contracted position. The upper torso should remain stationary and only the arms should move. The forearms should do no other work except for holding the bar; therefore do not try to pull down the bar using the forearms.","After a second at the contracted position squeezing your shoulder blades together, slowly raise the bar back to the starting position when your arms are fully extended and the lats are fully stretched. Inhale during this portion of the movement.","Repeat this motion for the prescribed amount of repetitions."],
    secondaryMuscles: ["biceps","middle back","shoulders"],
    images:           ["https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Wide-Grip_Lat_Pulldown/0.jpg","https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Wide-Grip_Lat_Pulldown/1.jpg"],
  },
  {
    id:               "Leg_Press",
    name:             "Leg Press",
    bodyPart:         "strength",
    target:           "quadriceps",
    equipment:        "machine",
    difficulty:       "beginner",
    instructions:     ["Using a leg press machine, sit down on the machine and place your legs on the platform directly in front of you at a medium (shoulder width) foot stance. (Note: For the purposes of this discussion we will use the medium stance described above which targets overall development; however you can choose any of the three stances described in the foot positioning section).","Lower the safety bars holding the weighted platform in place and press the platform all the way up until your legs are fully extended in front of you. Tip: Make sure that you do not lock your knees. Your torso and the legs should make a perfect 90-degree angle. This will be your starting position.","As you inhale, slowly lower the platform until your upper and lower legs make a 90-degree angle.","Pushing mainly with the heels of your feet and using the quadriceps go back to the starting position as you exhale.","Repeat for the recommended amount of repetitions and ensure to lock the safety pins properly once you are done. You do not want that platform falling on you fully loaded."],
    secondaryMuscles: ["calves","glutes","hamstrings"],
    images:           ["https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Leg_Press/0.jpg","https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Leg_Press/1.jpg"],
  },
  {
    id:               "Cable_Shoulder_Press",
    name:             "Shoulder Press",
    bodyPart:         "strength",
    target:           "shoulders",
    equipment:        "cable",
    difficulty:       "beginner",
    instructions:     ["Move the cables to the bottom of the towers and select an appropriate weight.","Stand directly in between the uprights. Grasp the cables and hold them at shoulder height, palms facing forward. This will be your starting position.","Keeping your head and chest up, extend through the elbow to press the handles directly over head.","After pausing at the top, return to the starting position and repeat."],
    secondaryMuscles: ["triceps"],
    images:           ["https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Shoulder_Press/0.jpg","https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Shoulder_Press/1.jpg"],
  },
  {
    id:               "Clean_Deadlift",
    name:             "Deadlift",
    bodyPart:         "olympic weightlifting",
    target:           "hamstrings",
    equipment:        "barbell",
    difficulty:       "beginner",
    instructions:     ["Begin standing with a barbell close to your shins. Your feet should be directly under your hips with your feet turned out slightly. Grip the bar with a double overhand grip or hook grip, about shoulder width apart. Squat down to the bar. Your spine should be in full extension, with a back angle that places your shoulders in front of the bar and your back as vertical as possible.","Begin by driving through the floor through the front of your heels. As the bar travels upward, maintain a constant back angle. Flare your knees out to the side to help keep them out of the bar's path.","After the bar crosses the knees, complete the lift by driving the hips into the bar until your hips and knees are extended."],
    secondaryMuscles: ["forearms","glutes","lower back","middle back","quadriceps","traps"],
    images:           ["https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Clean_Deadlift/0.jpg","https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Clean_Deadlift/1.jpg"],
  },
  {
    id:               "Single_Leg_Glute_Bridge",
    name:             "Glute Bridge",
    bodyPart:         "strength",
    target:           "glutes",
    equipment:        "body only",
    difficulty:       "beginner",
    instructions:     ["Lay on the floor with your feet flat and knees bent.","Raise one leg off of the ground, pulling the knee to your chest. This will be your starting position.","Execute the movement by driving through the heel, extending your hip upward and raising your glutes off of the ground.","Extend as far as possible, pause and then return to the starting position."],
    secondaryMuscles: ["hamstrings"],
    images:           ["https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Single_Leg_Glute_Bridge/0.jpg","https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Single_Leg_Glute_Bridge/1.jpg"],
  },
];
